export const A_Z = 0, Z_A= 1, MOST_RECENT=3, LEAST_RECENT=4;


export const OTHER_OPTIONS = [
    ['Text', 'text'],
    ['Color', 'color'],
    ['Text Align', 'textAlign'],
    ['Height', 'height'],
    ['Width', 'width'],
    ['Font Family', 'fontFamily'],
    ['Font Weight', 'fontWeight'],
    ['Display', 'display'],
    ['Background Color', 'backgroundColor'],
    ['Box Shadow', 'boxShadow'],
    ['Margin', 'margin'],
    ['Padding', 'padding'],
    ['Border', 'border'],
    ['Border Radius', 'borderRadius'],
    ['Font Size', 'fontSize'],
    ['Line Height', 'lineHeight'],
  ],
  BODY_OPTIONS = [
    ['Width', 'width'],
    ['Height', 'height'],
    ['Max Height', 'maxHeight'],
    ['Max Width', 'maxWidth'],
    ['Text Align', 'textAlign'],
    ['Font Family', 'fontFamily'],
    ['Border', 'border'],
    ['Background Color', 'backgroundColor'],
    ['Box Shadow', 'boxShadow'],
    ['Margin', 'margin'],
    ['Border Radius', 'borderRadius'],
    ['Padding', 'padding'],
    ['Display', 'display'],
    ['Position', 'position'],
    ['Background Image', 'backgroundImage'],
    ['Background Size', 'backgroundSize'],
    ['Background Repeat', 'backgroundRepeat'],
    ['Backdrop Filter', 'backdropFilter'],
    ['Background', 'background']
  ],
  
IMAGE_OPTIONS = [
    ['Background', 'backgroundImage'],
    ['Alt', 'alt'],
    ['Height', 'height'],
    ['Width', 'width'],
    ['Display', 'display'],
    ['Min Height', 'minHeight'],
    ['Background Size', 'backgroundSize'],
    ['Box Shadow', 'boxShadow'],
    ['Margin', 'margin'],
    ['Border Radius', 'borderRadius'],
    ['Padding', 'padding'],
  ],
  CONTAINER_OPTIONS = [
    ['Width', 'width'],
    ['Height', 'height'],
    ['Max Height', 'maxHeight'],
    ['Max Width', 'maxWidth'],
    ['Text Align', 'textAlign'],
    ['Font Family', 'fontFamily'],
    ['Border', 'border'],
    ['Background Color', 'backgroundColor'],
    ['Box Shadow', 'boxShadow'],
    ['Margin', 'margin'],
    ['Border Radius', 'borderRadius'],
    ['Padding', 'padding'],
    ['Display', 'display'],
    ['Background Image', 'backgroundImage'],
    ['Background Size', 'backgroundSize'],
    ['Background Repeat', 'backgroundRepeat'],
    ['Backdrop Filter', 'backdropFilter'],
]
  